from plots import *
from styles import *
from backend import *


streamlit_style()

if st.session_state['validated'] == True:
    st.title('💹 Line Charts')
    st.markdown("""---""")

    st.subheader("Expand the tabs to see the plots")
    st.subheader(" ")

    with st.expander('Per Customer Sales'):
        st.plotly_chart(plot_per_customer_sales())
        st.write("The following chart represents the total sales per customer.")

    st.subheader(' ')
    with st.expander('Sales in Peak Hours'):
        st.plotly_chart(plot_sales_per_hour())
        st.write(
            "The following chart represents the sale of the store in the peak hours.")

    st.subheader(' ')
    with st.expander('Sales Per Item'):
        st.plotly_chart(plot_sales_per_item())
        st.write(
            "The following chart represents the sale of the store generated by specific item.")


else:
    st.title("Kindly Log In!!")
